opsim:
  artifact:
    probability:
      mainstat:
        any: # Rarity
          flower:
            HP_Fixed:  100.0
          plume:
            ATK_Fixed: 100.0
          sands:
            HP_Percentage:  26.68
            ATK_Percentage: 26.66
            DEF_Percentage: 26.66
            Energy_Recharge: 10.00
            Elemental_Mastery: 10.00
          goblet:
            HP_Percentage:  19.25
            ATK_Percentage: 19.25
            DEF_Percentage: 19
            Elemental_Mastery:   2.50
            PhysicalDamageBonus: 5.00
            AnemoDamageBonus:    5.00
            GeoDamageBonus:      5.00
            ElectroDamageBonus:  5.00
            DendroDamageBonus:   5.00
            HydroDamageBonus:    5.00
            PyroDamageBonus:     5.00
            CryoDamageBonus:     5.00
          circlet:
            HP_Percentage:  22.00
            ATK_Percentage: 22.00
            DEF_Percentage: 22.00
            CritRate: 10.00
            CritDamage: 10.00
            HealingBonus: 10.00
            Elemental_Mastery: 4.00
    scaling:
      mainstat:
        5:
          HP_Fixed:       [717, 1530, 2342, 3155, 3967, 4780]
          ATK_Fixed:      [47, 100, 152, 205, 258, 311]
          HP_Percentage:  [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          ATK_Percentage: [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          DEF_Percentage:      [8.7, 18.6, 28.6, 38.5, 48.4, 58.3]
          PhysicalDamageBonus: [8.7, 18.6, 28.6, 38.5, 48.4, 58.3]
          ElementalDamageBonus: [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          AnemoDamageBonus:   [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          GeoDamageBonus:     [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          ElectroDamageBonus: [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          DendroDamageBonus:  [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          HydroDamageBonus:   [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          PyroDamageBonus:    [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          CryoDamageBonus:    [7.0, 14.9, 22.8, 30.8, 38.7, 46.6]
          Elemental_Mastery: [28.0, 59.7, 91.4, 123.1, 154.8, 186.5]
          Energy_Recharge:   [7.8, 16.6, 25.4, 34.2, 43.0, 51.8]
          CritRate:     [4.7,  9.9, 15.2, 20.5, 25.8, 31.1]
          CritDamage:   [9.3, 19.9, 30.5, 41.0, 51.6, 62.2]
          HealingBonus: [5.4, 11.5, 17.6, 23.7, 29.8, 35.9]
